# Generated by Django 2.0.13 on 2020-03-31 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nationalId', models.CharField(blank=True, max_length=63)),
                ('medicalCouncilId', models.CharField(blank=True, max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('medicineTakingHistory', models.CharField(max_length=255)),
                ('episodeType', models.CharField(choices=[('O', 'Online'), ('P', 'In Person')], default='P', max_length=1)),
                ('status', models.CharField(choices=[('P', 'In Progress'), ('C', 'Completed'), ('D', 'Discarded')], default='P', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgname', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nationalId', models.CharField(blank=True, max_length=63)),
                ('diseaseHistory', models.CharField(blank=True, default='', max_length=255)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=7)),
                ('height', models.DecimalField(blank=True, decimal_places=3, max_digits=7)),
                ('insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patinet_insurance_set', to='core.Insurance')),
                ('supplementalInsurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patinet_supplemental_set', to='core.Insurance')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'In Progress'), ('C', 'Completed'), ('D', 'Discarded')], default='P', max_length=1)),
                ('subject', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='treatment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Treatment'),
        ),
    ]
