# Generated by Django 3.0.2 on 2020-04-11 12:48

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_avatar_image),
        ),
        migrations.AlterField(
            model_name='patient',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.upload_avatar_image),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
