# Generated by Django 3.0.2 on 2020-04-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200428_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='description',
            field=models.CharField(blank=True, max_length=1023, null=True),
        ),
    ]
