# Generated by Django 3.0.2 on 2020-05-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
